version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ../config/server
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - movies-service-db

  movies-service-db:
    container_name: movies-service-db
    image: movies-service-db
    build:
      context: ../config/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=movies-service-db
      - POSTGRES_DB=same_db

  movies-service-api:
    container_name: movies-service-api
    image: movies-service-api
    build:
      context: ../movies-service
      dockerfile: Dockerfile
    ports:
      - 4001:4000
    depends_on:
      - movies-service-db
    links:
      - movies-service-db