version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ../config/server
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - movies-service-db

  movies-service-db:
    container_name: movies-service-db
    image: movies-service-db
    build:
      context: ../config/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=movies-service-db
      - POSTGRES_DB=movies-db

  movies-service-api:
    container_name: movies-service-api
    image: movies-service-api
    build:
      context: ../movies-service
      dockerfile: Dockerfile
    ports:
      - 4001:4000
    depends_on:
      - movies-service-db
    links:
      - movies-service-db

  cinema-catalog-service-db:
    container_name: cinema-catalog-service-db
    image: cinema-catalog-service-db
    build:
      context: ../config/db
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=cinema-catalog-service-db
      - POSTGRES_DB=cinema-catalog-db

  cinema-catalog-service-api:
    container_name: cinema-catalog-service-api
    image: cinema-catalog-service-api
    build:
      context: ../cinema-catalog-service
      dockerfile: Dockerfile
    ports:
      - 4002:4000
    depends_on:
      - cinema-catalog-service-db
      - movies-service-api
    links:
      - cinema-catalog-service-db
      - movies-service-api
    environment:
      - MOVIE_SERVICE_CONTAINER=movies-service-api